version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
